version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: postgres:latest
    volumes:
      - postgres_new_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5460:5432
    container_name: fastapi_postgresql

volumes:
    postgres_new_data:
